let baseUrl = 'https://server3.rvtechnologies.in/LokahiFishing_API/public/api/';

let imageUrl1 = 'http://54.74.233.110/storage/';
let imageUrl = 'http://54.74.233.110/';

const urls = {
  baseUrl,
  imageUrl,
  imageUrl1,
  login_url: 'login',
  register_url: 'register',
  check_login: 'check_login',
  user_data: 'user_data',
  videos: 'videos',
  register: 'register',
  my_profile: 'my-profile',
  edit_boat_info: 'edit-boat-info',
  edit_emergency_contacts: 'edit-emergency-contacts',
  complete_registration: 'complete_registration',
  get_profile: 'get_profile',
  update_profile: 'update_profile',
  forgot_password: 'forgot_password',
  verify_forgot_password_otp: 'verify_forgot_password_otp',
  update_password: 'update_password',
  change_password: 'change-password',
  getfriend_requests: 'friend-requests',
  getfriend_list: 'friend-list',
  respondtofriendrequest: 'respond-to-friend-request',
  forgotPassword: 'forgot_password',
  editProfile: 'edit-profile',
  removeResume: 'removeresume',
  changeEmail: 'change_email',
  changePhone: 'change_phone',
  getUserProfile: 'getuser',
  news: 'news',
  signs: 'signs',
  positions: 'positions',
  lcr_first: 'lcr-first-level-category',
  lcr_Second: 'lcr-second-level-category',
  lcr_third: 'lcr-third-level-category',
  lcr_fishes: 'lcr-fishes',
  weather: 'weather',
  method: 'method',
  save_lcr_report: 'save-lcr-report',
  lcr_list: 'lcr-list',
  update_lcr_report: 'update-lcr-report',
  comment_lcr: 'lcr-addComment',
  lcr_comments_listing: 'lcr-comments-listing',
  lcr_likes_listing: 'lcr-likes-listing',
  lcr_addlike: 'lcr-addlike',
  save_video:'save-video-sharing',
  save_photo_sharing:'save-photo-sharing',
  timeline: 'timeline',
  photoshareaddlike : 'photoshare-addlike',
  photoshare_like_list : 'photoshare-like-list',
  photoshare_addcomment : 'photoshare-addcomment', 
  photoshare_comment_list : 'photoshare-comment-list',
  leaderboard_fish_list :'leaderboard-fishes-list',
  leaderboard_ranking  : 'leaderboard-ranking',
  leaderboard_filter : 'leaderboard-filter' , 
  tournament_listing : 'tournament-listing',
  terms_and_condition : 'terms-and-condition',
  member_listing : 'member-listing',
};

export {urls};
